spring:
  url: "http://localhost:8080"

  server:
    port: 8080
    # address: 192.168.100.184

  datasource:
    # org.mariadb.jdbc.Driver
    # com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(bRfuF3Znt1SnimixwpfKp8lUXaTl9HyyjwrZpqxmD5I9tsIS73PbiYAd2p5Xu0vFjIzrAcdKhwqQrvWpXPo9TXFB6bO/8NYlflMza3ymQFV6YPJWzcPc6g==)
    username: ENC(Txf4MwWVQ2tJBiecIhaYWw==)
    password: ENC(Nvzs93v8dGSBctFdYOA8iA==)
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    redis:
      host: localhost
      port: 6379

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션
    defer-datasource-initialization: true

  jwt:
    secret: ENC(e1zXtOxodEDLDkWjqtwR/OibgDLT+GlirrMHhwkNIAJOC0I/09XPk5TS6GjmyU76)
#springdoc:
#  show-login-endpoint: true