spring:
  url: "http://localhost:8080"

  server:
    port: 8080
    # address: 192.168.100.184

  datasource:
    # org.mariadb.jdbc.Driver
    # com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demo?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: ssafy
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    redis:
      host: localhost
      port: 6379

  # jpa
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    # script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션
    defer-datasource-initialization: true

  jwt:
    secret: spring.jwt.secret=ieofs983289qa98we9ufs/
#springdoc:
#  show-login-endpoint: true